// Placeholder for future diff parsing utilities.
// The actual diff content is generated by git and returned to the frontend,
// where the React side uses the `diff` library for visual rendering.

#[allow(dead_code)]
pub fn is_binary_marker(patch: &str) -> bool {
    patch.contains("Binary files")
}
